### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by hannesm** [roburio/albatross#115]
somehow on FreeBSD, the albatross-stat ran into `Fatal error: exception Invalid_argument("List.combine")`, which in turn resulted in `albatrossd` unable to send more data to the stats daemon (and thus, a failure without cleanup of tap devices etc.).

**Comment by reynir** [comment]
Should we reopen this? In ee58e29bc25cbb67fb0439b59d4a87ce0b66bcdb I referenced this commit because it might fix the issue, and github is eager to close issues mentioned in commits...

**Comment by hannesm** [comment]
I think this is fine, since the List.combine is gone now :)
