### ISSUE TITLE
Systemd: include network.target in After=

### ISSUE THREAD

**Issue by reynir** [roburio/albatross#90]
On a system where the `service` bridge is configured by NetworkManager albatross fails to restore VMs after a reboot due to the bridge not being up:

```
Jan 03 15:02:20 solsort albatrossd[1877]: albatrossd: [ERROR] failed to create [vm: stub-resolver]: interface service does not exist
```

Likely, adding `network.target` to the list in `After=...` in the systemd service files will fix this. I have added `network.target` on the machine and will confirm whether this fixed the issue (after I have done some upgrades).

**Comment by hannesm** [comment]
Thanks for your report -- is this something we should add to the systemd file?

**Comment by reynir** [comment]
Yes, I think that would be a good idea.

For what it's worth it was not sufficient with my setup (bridge managed by NM) and I have added `NetworkManager-wait-online.service` as well.

**Comment by hannesm** [comment]
would you mind to push a PR? maybe putting the NetworkManager-wait-online as well (and describe in the README that if one doesn't use network manager to comment that bit out?)
